[package]
name = "lib"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.9.6"
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.8" }
base64 = "0.22.1"

